name: MLops ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-model:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/download-artifact@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../../requirements.txt

      - name: Run training model
        run: python train.py

      - name: Save the trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/house_regression_model.pkl
