name: MLops ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-model:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: . # ensure root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # ✅ correct action

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training model
        run: python CI/ci_training_model.py

      - name: Save the trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/house_regression_model.pkl
